//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_TRAMITES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADO_TRAMITES()
        {
            this.EXPEDIENTES_DIGITALES = new HashSet<EXPEDIENTES_DIGITALES>();
        }
    
        public int ID_ESTADO_TRAMITE { get; set; }
        public string ESTADO_DOCUMENTO_PERITO { get; set; }
        public string ESTADO_SOLICITUD { get; set; }
        public string ESTADO_PERMISO_CONSTRUCCION { get; set; }
        public string ESTADO_ARQUITECTURA { get; set; }
        public string ESTADO_BANHVI { get; set; }
        public string ESTADO_MUCAP { get; set; }
        public string DIS { get; set; }
        public string DESEMBOLSOS { get; set; }
        public string CASOS_FORMALIZADOS { get; set; }
        public string APC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPEDIENTES_DIGITALES> EXPEDIENTES_DIGITALES { get; set; }
    }
}
