//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPEDIENTES_DIGITALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPEDIENTES_DIGITALES()
        {
            this.UBICACION_EXPEDIENTES = new HashSet<UBICACION_EXPEDIENTES>();
        }
    
        public int ID_EXPEDIENTE_DIGITAL { get; set; }
        public int FK_CATEGORIA_BONO { get; set; }
        public string NOMBRE_EXPEDIENTE { get; set; }
        public int FK_OBRA { get; set; }
        public int FK_USUARIO { get; set; }
        public int FK_CLIENTE { get; set; }
        public string OBSERVACIONES { get; set; }
        public int FK_ESTADO_TRAMITE { get; set; }
        public int FK_REQUISITOS_INICIALES { get; set; }
    
        public virtual CATEGORIA_BONOS CATEGORIA_BONOS { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ESTADO_TRAMITES ESTADO_TRAMITES { get; set; }
        public virtual OBRAS OBRAS { get; set; }
        public virtual REQUISITOS_INICIALES REQUISITOS_INICIALES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UBICACION_EXPEDIENTES> UBICACION_EXPEDIENTES { get; set; }
    }
}
