//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        public int ID_FACTURA { get; set; }
        public int FK_CLIENTE { get; set; }
        public int FK_PROVEEDOR { get; set; }
        public int FK_OUTSOURCING { get; set; }
        public int FK_USUARIO { get; set; }
        public double SUB_TOTAL { get; set; }
        public double TOTAL { get; set; }
        public Nullable<double> IMPUESTOS { get; set; }
        public string DETALLE { get; set; }
        public string CONCEPTO { get; set; }
        public System.DateTime FECHA_FACTURA { get; set; }
        public double MONTO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual OUTSOURCING_S OUTSOURCING_S { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
