//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONARIOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ID_FUNCIONARIO { get; set; }
        public int CEDULA { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public int FK_PUESTO { get; set; }
        public string PROVINCIA { get; set; }
        public string CANTON { get; set; }
        public string DISTRITO { get; set; }
        public string OTRAS_SEÑAS { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string NACIONALIDAD { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public Nullable<int> TELEFONO_1 { get; set; }
        public Nullable<int> TELEFONO_2 { get; set; }
        public Nullable<System.DateTime> FECHA_CESANTIA { get; set; }
        public string SEXO { get; set; }
    
        public virtual PUESTOS PUESTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
