//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTAS_OUTSOURCING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTAS_OUTSOURCING()
        {
            this.OUTSOURCING_S = new HashSet<OUTSOURCING_S>();
        }
    
        public int ID_LISTA_OUTSOURCING { get; set; }
        public string NOMBRE_SERVICIO { get; set; }
        public int SALARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUTSOURCING_S> OUTSOURCING_S { get; set; }
    }
}
