//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDORES()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
            this.PAGOS_X_PROVEEDORES = new HashSet<PAGOS_X_PROVEEDORES>();
        }
    
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE_PROVEEDOR { get; set; }
        public int TELEFONO_1 { get; set; }
        public Nullable<int> TELEFONO_2 { get; set; }
        public string CEDULA_JURIDICA { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string PROVINCIA { get; set; }
        public string CANTON { get; set; }
        public string DISTRITO { get; set; }
        public string OTRAS_SENAS { get; set; }
        public string OBSERVACIONES { get; set; }
        public string SERVICIO_PROVEEDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS_X_PROVEEDORES> PAGOS_X_PROVEEDORES { get; set; }
    }
}
