//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISITOS_INICIALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUISITOS_INICIALES()
        {
            this.EXPEDIENTES_DIGITALES = new HashSet<EXPEDIENTES_DIGITALES>();
        }
    
        public int ID_REQUISITO { get; set; }
        public string COPIA_CEDULA { get; set; }
        public string PROPIEDADES { get; set; }
        public string COPIA_RECIBOS_SERVICIOS_PUBLICOS { get; set; }
        public string BONOS_ANTERIORES { get; set; }
        public string CERTIFICACION_IMPUESTOS { get; set; }
        public string EXAMEN_POZO { get; set; }
        public string CERTIFICACION_ESTADO_CIVIL { get; set; }
        public string TERRENO_LOTE { get; set; }
        public string REPORTE_SICERE { get; set; }
        public string CONSTANCIA_CONTADOR { get; set; }
        public string CONSTANCIA_SALARIO { get; set; }
        public string ASADA { get; set; }
        public int FK_CLIENTE { get; set; }
        public string PLANO_CATASTRO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPEDIENTES_DIGITALES> EXPEDIENTES_DIGITALES { get; set; }
    }
}
