//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBICACION_EXPEDIENTES
    {
        public int ID_UBICACION_EXPEIENTE { get; set; }
        public string NOMBRE_UBICACION { get; set; }
        public int FK_USUARIO { get; set; }
        public string DETALLE_UBICACION { get; set; }
        public int FK_EXPEDIENTE { get; set; }
    
        public virtual EXPEDIENTES_DIGITALES EXPEDIENTES_DIGITALES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
